export const chartData = {
    traffic: [
        { zone: "Kuala Lumpur", value: 50, timestamp: "2024-03-01 08:30 AM" },
        { zone: "Petaling Jaya", value: 30, timestamp: "2024-03-02 09:15 AM" },
        { zone: "Shah Alam", value: 20, timestamp: "2024-03-03 07:45 AM" },
        { zone: "Penang", value: 45, timestamp: "2024-03-04 10:00 AM" },
        { zone: "Johor Bahru", value: 35, timestamp: "2024-03-05 11:30 AM" },
        { zone: "Ipoh", value: 40, timestamp: "2024-03-06 06:50 AM" },
        { zone: "Kota Kinabalu", value: 55, timestamp: "2024-03-07 12:10 PM" },
    ],
    waste: [
        { area: "KL City Centre", value: 85, timestamp: "2024-03-01 06:00 AM" },
        { area: "Ampang", value: 78, timestamp: "2024-03-02 07:10 AM" },
        { area: "Cheras", value: 80, timestamp: "2024-03-03 05:30 AM" },
        { area: "Subang Jaya", value: 90, timestamp: "2024-03-04 08:15 AM" },
        { area: "Cyberjaya", value: 88, timestamp: "2024-03-05 09:45 AM" },
    ],
    flood: [
        { region: "Klang Valley", value: 60, timestamp: "2024-03-01 03:00 PM" },
        { region: "East Coast (Kelantan, Terengganu, Pahang)", value: 90, timestamp: "2024-03-02 02:45 PM" },
        { region: "Penang", value: 40, timestamp: "2024-03-03 01:30 PM" },
        { region: "Sarawak", value: 30, timestamp: "2024-03-04 04:00 PM" },
    ],
};

export const malaysiaCities = [
    'Kuala Lumpur',
    'Petaling Jaya',
    'Penang',
    'Johor Bahru',
    'Ipoh',
    'Malacca',
    'Kuching',
    'Kota Kinabalu',
    'Shah Alam',
    'Subang Jaya',
    'Klang',
    'Seremban',
    'Alor Setar',
    'Kuantan',
    'Miri',
    'Taiping',
    'Sandakan',
    'Tawau',
    'Sibu',
    'Kangar',
    'Putrajaya',
    'George Town',
    'Kuala Terengganu',
    'Melaka',
    'Kuala Selangor',
    'Batu Pahat',
    'Muar',
    'Kulai',
    'Pasir Gudang',
    'Skudai',
    'Kota Bharu',
    'Kuala Pilah',
    'Tampin',
    'Port Dickson',
    'Nilai',
    'Rawang',
    'Semenyih',
    'Banting',
    'Sepang',
    'Cyberjaya',
    'Puchong',
    'Cheras',
    'Ampang',
    'Kajang',
    'Sungai Petani',
    'Kulim',
    'Bagan Serai',
    'Parit Buntar',
    'Lumut',
    'Teluk Intan',
    'Tanjung Malim',
    'Raub',
    'Bentong',
    'Mentakab',
    'Temerloh',
    'Jerantut',
    'Kuala Lipis',
    'Gua Musang',
    'Kuala Krai',
    'Pasir Mas',
    'Tanah Merah',
    'Machang',
    'Jeli',
    'Kuala Berang',
    'Marang',
    'Dungun',
    'Kemaman',
    'Paka',
    'Cukai',
    'Besut',
    'Setiu',
    'Hulu Terengganu',
    'Kuala Nerus',
    'Kuala Dungun',
    'Kuala Besut',
    'Kuala Kemaman',
    'Kuala Setiu',
    'Kuala Hulu Terengganu',
];
